### ISSUE TITLE
Processes don't always terminate

### ISSUE THREAD

**Issue by compleathorseplayer** [dmolina/DaemonMode.jl#12]
Hi.  I have been happily using this application, but a bug has crept in (I don't know what I did differently).

Some of the time, if I send a job to the daemon using 'at' (the cron daemon in linux) the jobs execute OK but don't terminate, and then seem to continue indefinitely, continuing to create bigger and bigger files (as in many tens of GBs) in the spool.

I made sure to include quit() at the end of all of my scripts, but is there another way to make sure they exit?

Also, has anyone else had this problem?

Thanks for any help.

PS After writing this, I found out what seems to be the problem, which was the server to which my program was connecting, which was hanging.   When the server/connection is OK the program terminates as it should, so no bug, really (except perhaps for the filling up of my hard-drive when this happens!).
I think it would be very helpful if it were possible to set a timeout on the daemon-executed script.

PPS  Since writing this, I have found a solution for Linux users, which is the 'timeout' utility 
(see https://stackoverflow.com/questions/2387485/limiting-the-time-a-program-runs-in-linux)
In this case, that would amount to:
```
timeout 10s julia --startup-file=no -e 'using DaemonMode; runargs()' program.jl <arguments>
```

**Comment by dmolina** [comment]
I like that you are happy using it.

I agree that the daemon should have a timeout, but the problem is that the client could takes a lot of time in processing. I think that I could add an optional timeout, but it should not be anyone by default, because only the user that run the server should have an idea of how much time it should be limited. Do you agree?
