### ISSUE TITLE
Throw on failure to connect to server

### ISSUE THREAD

**Issue by altre** [dmolina/DaemonMode.jl#18]
I'm not quite sure, but wouldn't it be better to fail with an exception when not being able to connect to the server, instead of just logging:

https://github.com/dmolina/DaemonMode.jl/blob/24930ead0bd536f848c2a3251a0faec284fe1356/src/DaemonMode.jl#L256

My current use case is a simple bash script which falls back to using Julia without the daemonmode if not installed or running. I would then need to parse the output in stderr instead of using the return value.

**Comment by dmolina** [comment]
I have just update the code to return the code when there is a simple error (as it cannot connect to the server, or the file is not found). It is in the current master version. 
I want to return also when any exception is returned for next version, but it could take more time, because I have to change the communications.

**Comment by dmolina** [comment]
The last version is better for scripting. It returns the error code if there is an error in the case of not connection or Exception.
